### ISSUE TITLE
Implicit call of function greybox:::forecast causes code break

### ISSUE THREAD

**Issue by Steviey** [config-i1/greybox#59]
_Ubuntu 16.x LTS, R latest (CLI/batch-mode), greybox latest_

I can't provide a reproduce-able example yet, but it seems
calling **fabletools::forecast()** can trigger an implicit, automatic call of **greybox:::forecast()**, which then leads to a code break. Im loading the libraries in the order discussed here: https://github.com/config-i1/greybox/issues/54
The effect... 
Error in meanf(object, h = h, level = level, fan = fan, lambda = lambda,  : 
  unused arguments...
Calls: bAlgos ... predict.default -> forecast -> forecast.default -> forecast.ts
`[90m     [39m█
[90m  1. [39m├─global::bAlgos(i, f, "testing")
[90m  2. [39m│ ├─base::do.call(...)
[90m  3. [39m│ └─(function (seed, dataset, metric, control, f, i, algo, only_one_predictor_exception, ...
[90m  4. [39m│   └─`%>%`(...)
[90m  5. [39m├─fabletools::forecast(...) <--- this is intended
[90m  6. [39m├─greybox:::forecast.default(...) <-- this is not intended
[90m  7. [39m│ ├─stats::predict(object, ...)
[90m  8. [39m│ └─forecast:::predict.default(object, ...)
[90m  9. [39m│   ├─forecast::forecast(object, ...)
[90m 10. [39m│   └─forecast:::forecast.default(object, ...)
[90m 11. [39m│     └─forecast:::forecast.ts(object, ...)
[90m 12. [39m└─(function () ...
[90m 13. [39m  └─lobstr::cst()`

For now, I will try to unload and reload greybox during runtime- to hint this behavior. Are there any other tricks available?

**Comment by config-i1** [comment]
Thanks for the bug report. I've switched off the registration of methods of greybox now. Can you please check if the development version works for you? If yes, I'll submit it on CRAN.

Also, @robjhyndman and I have submitted a request to add forecast to the generics package: https://github.com/r-lib/generics/issues/63 . The idea is to move it away from our packages so that it does not cause conflicts like this. So far, we have not heard anything from the maintainers of the package. If this happens at some point, you won't have issues like this.

**Comment by Steviey** [comment]
Ahoi!
The strange thing is, I can't reproduce this behavior in RStudio. 
It's a 'cli-only effect'. I will test the dev-version on cli... will take some time.

**Comment by Steviey** [comment]
Hello Ivan, I can confirm, this works so far for me on cli.
